small tox fixes
* remove py26: it no longer used in gates, and fails the tests on:

    (dt.datetime.now() - time_before).total_seconds(),
    AttributeError: 'datetime.timedelta' object has no
    attribute'total_seconds'`

* don't generate __pycache__ folders

Change-Id: Ifce1e77012bc3be7785597ab84b998209b866ae8