Fix an action execution controller test
* test_get_all_with_and_without_output failed sometimes failed on
  Python 3.7 with a weird error coming from simplejson library:
  "AttributeError: 'MagicMock' object has no attribute 'items'"
  It seems like that the mock object used in the test got broken
  magically sometimes after the first use. So splitting the test
  into two solved the issue.

Change-Id: Ic2e0ad75b666dd4c258764018dd68d0ef0b032a8
(cherry picked from commit 9a60cd62d2d3ebd7706cdc4dec9f3d6f5ab5c9f8)