tempest: fix dir_path
This patch fix the dir_path that helps to get the directory of
Mistral resources.

Without this patch, this is what we get when running Tempest:

IOError: [Errno 2] No such file or directory:
'/usr/lib/python2.7/site-packages/mistral_mistral/tests/resources/openstack/action_collection_wb.yaml'

With this patch:
/usr/lib/python2.7/site-packages/mistral/tests/resources/openstack/action_collection_wb.yaml
This path is correct and Tempest runs successfully.

Change-Id: Ie4bd3db8a4e729f7937a6f3c099d7c25abffcb1b
Closes-Bug: #1568413
(cherry picked from commit 99edd171057daf29d4bf66cafdf282259fbd1e8b)