Update requirements to include oauthlib
This library is required for python-keystoneclient oauth resources
(e.g., consumers, request tokens, etc). Without this library, mistral
logs an error since keystoneauth treats the oauthlib library as an
optional dependency:

  Failed to create action: keystone.oauth1.consumers_build_url:
  NotImplementedError: To use 'consumers' oauthlib must be installed

This commit adds the oauthlib package to requirements.txt so that
mistral doesn't log ERRRORs building the action map.

Change-Id: Ib172dd8fb122696072c38e9c78e0e07b5e38f222