Add extra checks for the existance of executor_callback
In version of oslo.messaging > 4.6.1, the __call__ method of
dispatcher.RPCDispatcher no longer exists. It is now a 'method-wrapper'
from the "object" object.

Calling inspect.getargspec on a method-wrapper doesn't work
TypeError: <method-wrapper '__call__' of ABCMeta object at 0x2cc3650> is not a Python function

Change-Id: Ie2ca1a2b9163a5edfe1e779cff462692197a471d