Comparision opeartor has been changed.
While creating policy '>' operator is used,
due to which in py34 exception is occurred when
variable is provided from input parameter.

Exception was
TypeError: unorderable types: str() > int()

TODO: Add more unit test to catch such scenarios.

Partially-Implements: blueprint mistral-py3
Change-Id: I2c652812ae4a04cd7610f2a6684da76c582a4e32