Fix unit test failures caused by type mismatch
Currently unit tests are failing because of the following type mismatch
detected.

testtools.matchers._impl.MismatchError: '{'k2', 'k1'}' is not an
instance of list

This change fixes that error.

Change-Id: I8ecedd341ba45d1919c9073dda8b2fc390306a52