Fix more unit tests in py34 job
- fix: 'dict_values' object does not support indexing
- fix: 'ValueError' object has no attribute 'message'
- fix: RuntimeError: dictionary changed size during iteration

Change-Id: I3581783b84a6785c8d5ad07cbd2d5cb190c73d85