Raise NotImplementedError instead of NotImplemented
NotImplementedError is the name of the exception
(https://docs.python.org/2/library/exceptions.html).
NotImplemented is the name of a constant
(https://docs.python.org/2/library/constants.html).
>>> raise NotImplemented()
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    raise NotImplemented()
TypeError: 'NotImplementedType' object is not callable
>>> raise NotImplementedError()
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    raise NotImplementedError()
NotImplementedError
This patch fix it.

Change-Id: I1748706510c0d558c3fdca4ff822521c5adb6d97
Closes-Bug: #1339855