Correct the string formatting in a info log message
It should be "%s," not just "%,". The error observed was something
like...

ValueError: unsupported format character ',' (0x2c) at index 91

Closes-Bug: #1764696
Change-Id: I601c8640cec857746c2c17f94116da890f4d65e0
(cherry picked from commit 15e95d9b3cc7ce8cbe8de22ef80e8230f22107ee)