Do not parse updated_at for task if it was not updated
Currently if we try to get task from db, that was not updated yet
we get an error like:

YaqlEvaluationException: Can not evaluate YAQL expression
[expression=task().result.content, error='NoneType' object has no
attribute 'isoformat', data={}]

So we need to check if updated_at attr is not None, and do not force
parsing the attribute.

Change-Id: I7d5a068bd217c826891402a94da0a588beee8547
Closes-bug: #1729685